title: La Nuit du Code Citoyen
email: salut@lesbricodeurs.fr
description: > # this means to ignore newlines until "baseurl:"
  La Nuit du Code Citoyen est un marathon d'innovation les 4 et 5 mars 2017 associant thématiques citoyennes et 
  technologies avancées en simultané dans plusieurs villes de pays francophones. L’événement est suivi d’un 
  programme d’accompagnement sur la durée.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: lesbricodeurs
github: lesgeeksdudimanche
instagram: lesbricodeurs
facebook: lesbricodeurs


# Build settings
markdown: kramdown
theme: 
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
